# Generated by Django 4.2.7 on 2023-11-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripción')),
                ('subject', models.CharField(max_length=256, verbose_name='Asunto')),
                ('body', models.CharField(max_length=4096, verbose_name='Cuerpo')),
                ('email_from', models.CharField(max_length=256, verbose_name='Correo origen')),
                ('is_html', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Asunto')),
                ('body', models.CharField(max_length=4096, verbose_name='Cuerpo')),
                ('email_to', models.CharField(max_length=256, verbose_name='Correo destino')),
                ('email_from', models.CharField(max_length=256, verbose_name='Correo origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.template')),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
                'ordering': ['id'],
            },
        ),
    ]
